### PR TITLE
added topology.xml and buttonmap.xml

### PR DESCRIPTION
**Pull request by Heckie75**
Added topogogy.xml and buttonmap.xml especially in order to make special keys like ```start```, ```select``` and ```option``` work. See also https://github.com/kodi-game/game.libretro.atari800/issues/4

@garbear

### CODE REVIEW

**Comment by garbear** [comment]
Nice!

The XML is meant to represent the "source of truth" of the cpp. This is because libretro doesn't have as extensive or consistent of an input API, so we have to extract a lot of the data by hand.

In this case, the source is:

* https://github.com/libretro/libretro-atari800/blob/master/libretro/libretro-core.c
* https://github.com/libretro/libretro-atari800/blob/master/libretro/core-mapper.c

First, lets find the device map in the source. It is:

https://github.com/libretro/libretro-atari800/blob/master/libretro/libretro-core.c#L26-L27

```c++
#define RETRO_DEVICE_ATARI_KEYBOARD RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_KEYBOARD, 0)
#define RETRO_DEVICE_ATARI_JOYSTICK RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1)
```

This uses libretro's fundamental device abstraction. See https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L86-L102.

So the buttonmap should be:

```xml
<controller id="game.controller.atari.2600" type="RETRO_DEVICE_JOYPAD" subclass="1">
<controller id="game.controller.keyboard" type="RETRO_DEVICE_KEYBOARD" subclass="0">
```

Then the topology. There are four ports:

https://github.com/libretro/libretro-atari800/blob/master/libretro/libretro-core.c#L104-L110

```c++
    static const struct retro_controller_info ports[] = {
      { p1_controllers, 2  }, // port 1
      { p2_controllers, 2  }, // port 2
      { p3_controllers, 2  }, // port 3
      { p4_controllers, 2  }, // port 4
      { NULL, 0 }
    };
```

so topology.xml should have ports "3" and "4".

The rest of the buttonmap is a little harder. The mapping is here:

https://github.com/libretro/libretro-atari800/blob/master/libretro/core-mapper.c#L407

```c++
for (i = 0; i < (RETRO_DEVICE_ID_JOYPAD_R3+1); i++)
```

It scans for every button on the retropad. So the buttonmap should have entries for all 16 buttons:

https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L188-L203

```c++
#define RETRO_DEVICE_ID_JOYPAD_B        0
#define RETRO_DEVICE_ID_JOYPAD_Y        1
#define RETRO_DEVICE_ID_JOYPAD_SELECT   2
#define RETRO_DEVICE_ID_JOYPAD_START    3
#define RETRO_DEVICE_ID_JOYPAD_UP       4
#define RETRO_DEVICE_ID_JOYPAD_DOWN     5
#define RETRO_DEVICE_ID_JOYPAD_LEFT     6
#define RETRO_DEVICE_ID_JOYPAD_RIGHT    7
#define RETRO_DEVICE_ID_JOYPAD_A        8
#define RETRO_DEVICE_ID_JOYPAD_X        9
#define RETRO_DEVICE_ID_JOYPAD_L       10
#define RETRO_DEVICE_ID_JOYPAD_R       11
#define RETRO_DEVICE_ID_JOYPAD_L2      12
#define RETRO_DEVICE_ID_JOYPAD_R2      13
#define RETRO_DEVICE_ID_JOYPAD_L3      14
#define RETRO_DEVICE_ID_JOYPAD_R3      15
```

The lower-case part of the buttonmap is the "feature name" found in the [controller topology project](https://github.com/kodi-game/controller-topology-project):

https://github.com/kodi-game/controller-topology-project/blob/master/addons/game.controller.atari.2600/resources/layout.xml

Those entries should be matched up in buttonmap.xml. If not everything fits, then game.controller.atari.2600 should be extended, or a new controller add-on introduced.

Note that the emulator uses the analog sticks too, so those could be mapped as well:

https://github.com/libretro/libretro-atari800/blob/master/libretro/core-mapper.c#L437-L439

```
//emulate Joy1 with joy analog right 
ar[0][0] = (input_state_cb(0, RETRO_DEVICE_ANALOG, RETRO_DEVICE_INDEX_ANALOG_RIGHT, RETRO_DEVICE_ID_ANALOG_X));
ar[0][1] = (input_state_cb(0, RETRO_DEVICE_ANALOG, RETRO_DEVICE_INDEX_ANALOG_RIGHT, RETRO_DEVICE_ID_ANALOG_Y));
```

Also, you could add mouse support:

https://github.com/libretro/libretro-atari800/blob/master/libretro/core-mapper.c#L514C5-L521C5

```c++
mouse_wu   = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_WHEELUP);
mouse_wd   = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_WHEELDOWN);
mouse_x    = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_X);
mouse_y    = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_Y);
mouse_l    = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_LEFT);
mouse_r    = input_state_cb(0, RETRO_DEVICE_MOUSE, 0, RETRO_DEVICE_ID_MOUSE_RIGHT);
```

**Comment by Heckie75** [comment]
@garbear I have made some changes. I changed to ```game.controller.default``` in order to be able to map all buttons. Now it is possible to use _start_ , _select_ buttons, _option_ button and also others in order to open a menu, a virtual keyboard etc. 

However, I haven't figured out how to map the analog stick.

In addition I', not sure about the mouse, especially ```RETRO_DEVICE_ID_MOUSE_X```, ```RETRO_DEVICE_ID_MOUSE_Y``` and the missing _pointer_. I have no idea how to test it.

**Comment by garbear** [comment]
@Heckie75 I found another user trying to get Atari 800 working: https://forum.kodi.tv/showthread.php?tid=376031

We need controller profiles for atari 800 and atari 5200 controllers. Can you link my any pictures or documentation of these? I've never actually used either.

**Comment by Heckie75** [comment]
@garbear I pushed this merge request with bottonmap and topoloy months ago. Both work for me. Why hasn't it been merged yet?

**Comment by garbear** [comment]
It would be nice if we had atari 800/5200 controllers instead of using game.default, but this fixes input, so I'll merge and we can improve later.

**Comment by garbear** [comment]
Sorry it took so long to merge, totally forgot about this one until the forum atari800 user popped up and I rediscovered this.

For future reference, I made the following changes (https://github.com/kodi-game/game.libretro.atari800/commit/be0c949a67566eefb0a695a1bba835d5389a5a8e):

* Added newlines to files (this makes IDEs happy)
* Moved keyboard and mouse to beginning of topology for coniistency with other cores
* Added controller IDs to &lt;requires> tag in addon.xml.in

I'll do a release of atari800 so this change will go out on the mirrors.

EDIT: Version 3.1.0.33 has the buttonmaps.

**Comment by garbear** [comment]
@Heckie75 The forum user and I are working on Atari 800 controller profiles so the user can see the historic controller in the GUI attached to the Atari 800 instead of an anachronistic xbox controller: https://forum.kodi.tv/showthread.php?tid=376031&pid=3182024#pid3182024

Once we create the profiles would you be able to update the XML here to use the atari controllers?

**Comment by garbear** [comment]
I got swamped with work and travel the last 3 months, but I'm now pushing out the best of our work so far to production servers. Testing will be possible on all platforms.

New tracking issue here: https://github.com/kodi-game/controller-topology-project/issues/303

**Pull request merged**
